@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "זה מפוצץ בספרים על\n"
	.string "פוקימונים.$"

Text_NothingButPokemonBooks::
	.string "כל הספרים כאן\n"
	.string "קשורים לפוקימונים$"

Text_ATownMap::
	.string "מפה של העיר.$"

Text_PokeMartShelf::
	.string "וואוו!\n"
	.string "מלא דברים של פוקימונים!$"

Text_DishesPlatesNeatlyLinedUp::
	.string "הצלחות והכלים מסודרים\n"
	.string "מאוד יפה.$"

Text_Kitchen::
	.string "זה מריח נהדר!\n"
	.string "מישהו בישל כאן.$"

Text_Dresser::
	.string "זוהי ארונית מאוד יפה.\n"
	.string "היא יכולה להחזיק המון דברים.$"

Text_Snacks::
	.string "יש כאן ערימה של חטיפים.$"

Text_PokemartSign::
	.string "כל מה שתצטרכו עבור פוקימונים!\n"
	.string "סופרמרקט פוקימונים$"

Text_PokecenterSign::
	.string "ריפאו את הפוקימונים שלכם!\n"
	.string "מרכז רפואי לפוקימונים$"

Text_Indigo_UltimateGoal::
	.string "רמת אינדיגו\p"
	.string "המטרה הסופית של כל המאמנים!\n"
	.string "מרכז ליגת הפוקימונים$"

Text_Indigo_HighestAuthority::
	.string "רמת אינדיגו\p"
	.string "הסמכות הפוקימונית הגובהה ביותר!\n"
	.string "מרכז ליגת הפוקימונים$"

Text_Food::
	.string "זה צריך להיות ארוז עם כל מיני\n"
	.string "דברים טעימים לאכול.$"

Text_Blueprints::
	.string "זהו תדפיס של תוכנית כלשהי.\n"
	.string "יש פה תרשימים וכיתובים שונים.$"

Text_Painting::
	.string "זוהי תמונה יפה של פוקימונים.\n"
	.string "הפוקימון נראה מאוד שמח.$"

Text_PowerPlantMachine::
	.string "מה זו המכונה הזו?\n"
	.string "כדאי שלא להתעסק איתה!$"

Text_Telephone::
	.string "זהו טלפון.\n"
	.string "כדאי שלא להשתמש בו.$"

Text_Computer::
	.string "יש כאן המון מילים ומספרים\n"
	.string "שלא ממש עושים שכל…$"

Text_AdvertisingPoster::
	.string "זוהי פרסומת על\n"
	.string "כל מיני מוצרים.$"

Text_TastyFood::
	.string "איזה ריח טעים!\n"
	.string "עושה לי כרכורים בבטן!$"

Text_TrashBin::
	.string "בתוך זה…\n"
	.string "……\p"
	.string "אין כלום!$"

Text_Cup::
	.string "זוהי כוס עם סימן\n"
	.string "של פוקימון עליה.$"

Text_PolishedWindow::
	.string "החלון מבריק ומצוחצח.$"

Text_BeautifulSkyWindow::
	.string "מחוץ לחלון…\p"
	.string "השמיים נראים פשוט\n"
	.string "יפהפיים.$"

Text_BlinkingLights::
	.string "אורות שונים ומשונים\n"
	.string "מהבהבים שוב ושוב.$"

Text_NeatlyLinedUpTools::
	.string "כל מיני כלים מסודרים\n"
	.string "בצורה יפה.$"

Text_ImpressiveMachine::
	.string "זוהי מכונה כלשהי.\n"
	.string "היא מאוד מרשימה.$"

Text_VideoGame::
	.string "זהו המחשק הכי חדש!\n"
	.string "נראה ממש כיף!$"

Text_Burglary::
	.string "נראה שיש כאן סימנים\n"
	.string "שמישהו פרץ לכאן…$"

Text_PlayerFacingTVScreen::
	.string "יש פוקימנון בטלויזיה!\n"
	.string "נראה שהוא נהנה מאוד.$"
