gOtherText_NewName::
    .string "אחר$"

gNameChoice_Green::
    .string "גרין$"

gNameChoice_Red::
    .string "רד$"

gNameChoice_Leaf::
    .string "עלה$"

gNameChoice_Fire::
    .string "אש$"

gNameChoice_Gary::
    .string "גרי$"

gNameChoice_Kaz::
    .string "קאז$"

gNameChoice_Toru::
    .string "טורו$"

gNameChoice_Ash::
    .string "אש$"

gNameChoice_Kene::
    .string "קן$"

gNameChoice_Geki::
    .string "גקי$"

gNameChoice_Jak::
    .string "ג'ק$"

gNameChoice_Janne::
    .string "ג'יין$"

gNameChoice_Jonn::
    .string "ג'ון$"

gNameChoice_Kamon::
    .string "קמון$"

gNameChoice_Karl::
    .string "קרל$"

gNameChoice_Taylor::
    .string "טיילור$"

gNameChoice_Oscar::
    .string "אוסקר$"

gNameChoice_Hiro::
    .string "הירו$"

gNameChoice_Max::
    .string "מקס$"

gNameChoice_Jon::
    .string "ג'ון$"

gNameChoice_Ralph::
    .string "רלף$"

gNameChoice_Kay::
    .string "קאי$"

gNameChoice_Tosh::
    .string "טוש$"

gNameChoice_Roak::
    .string "רואק$"

gNameChoice_Omi::
    .string "אומי$"

gNameChoice_Jodi::
    .string "ג'ודי$"

gNameChoice_Amanda::
    .string "אמנדה$"

gNameChoice_Hillary::
    .string "הילרי$"

gNameChoice_Makey::
    .string "מאקי$"

gNameChoice_Michi::
    .string "מיצ'י$"

gNameChoice_Paula::
    .string "פאולה$"

gNameChoice_June::
    .string "ג'ון$"

gNameChoice_Cassie::
    .string "קאסי$"

gNameChoice_Rey::
    .string "ריי$"

gNameChoice_Seda::
    .string "סאדה$"

gNameChoice_Kiko::
    .string "קיקו$"

gNameChoice_Mina::
    .string "מינה$"

gNameChoice_Norie::
    .string "נורי$"

gNameChoice_Sai::
    .string "סאי$"

gNameChoice_Momo::
    .string "מומו$"

gNameChoice_Suzi::
    .string "סוזי$"

gNewGame_HelpDocs1::
    .string "להלן הסבר קצר על הכפתורים\n"
    .string "לפי סדר החשיבות שלהם.$"

gNewGame_HelpDocs2::
    .string "להזיז את הדמות.\n"
    .string "לבחור פריטים שונים\n"
    .string "בתפריטים.$"

gNewGame_HelpDocs3::
    .string "משמש לבחירה, לבדוק\n"
    .string "דברים, לשוחח, ולזרז טקסט.$"

gNewGame_HelpDocs4::
    .string "משמש ליציאה, ביטול בחירה,\n"
    .string "או ביטול מצב.$"

gNewGame_HelpDocs5::
    .string "לחצו על מקש זה כדי לפתוח\n"
    .string "את התפריט.$"

gNewGame_HelpDocs6::
    .string "משמש להזזת פריטים או לשימוש\n"
    .string "בפריט שנבחר קודם לכן.$"

gNewGame_HelpDocs7::
    .string "אם תצטרכו עזרה באיך\n"
    .string "לשחק, או כיצד לעשות דברים,\n"
    .string "לחצו על כפתור L או R.$"

gOakText_AskPlayerGender::
    .string "אמרו לי, אתם אתם בן?\n"
    .string "או האם אתם בת?$"

gNewGameAdventureIntro1::
    .string "בעולם שאתם עומדים להיכנס אליו,\n"
    .string "תצאו להרפתקה גדולה\n"
    .string "שבה אתם הגיבורים.\n"
    .string "\n"
    .string "תדברו עם אנשים ותבדקו חפצים בכל מקום\n"
    .string "אליו תגיעו, אם זה בערים, דרכים,\n"
    .string "או מערות. תאספו מידע ורמזים\n"
    .string "מכל מקור.$"

gNewGameAdventureIntro2::
    .string "דרכים חדשות יפתחו לכם אם תעזרו\n"
    .string "לאנשים בעת צרה, תגברו על אתגרים,\n"
    .string "ותפתרו תעלומות.\n"
    .string "\n"
    .string "לפעמים אחרים יאתגרו אתכם\n"
    .string "ויצורי פרא יתקפו אתכם.\n"
    .string "יהיו אמיצים ותמשיכו עד שתצליחו.$"

gNewGameAdventureIntro3::
    .string "בהרפתקה שלכם, אנו מקווים\n"
    .string "שתקיימו איטרקציה עם כל מיני\n"
    .string "אנשים ותשיגו צמיחה אישית.\n"
    .string "זו המטרה הגדולה ביותר.\n"
    .string "\n"
    .string "לחצו על כפתור A,\n"
    .string "ושההרפתקה תתחיל!$"

gOakText_WelcomeToTheWorld::
    .string "שלום לך!\n"
    .string "נעים מאוד להכיר!\pברוכים הבאים לעולם של הפוקימונים!\pשמי אלון.\pלעיתים אנשים מכנים אותי\n"
    .string "הפרופסור של הפוקימונים.\p$"

gOakText_WorldInhabited1::
    .string "העולם הזה…$"

gOakText_WorldInhabited2::
    .string "…מיושב לאורכו ורוחבו על ידי\n"
    .string "יצורים הנקראים פוקימונים.\p$"

gOakText_PetsBattlingStudy::
    .string "עבור חלק מהאנשים, פוקימונים הם\n"
    .string "חיות מחמד. ואחרים משתמשים בהם לקרבות.\pומה לגביי?\pובכן אני חוקר פוקימונים כמקצוע.\p$"

gOakText_TellMeALittleAboutYourself::
    .string "אבל ראשית, ספרו לי קצת\n"
    .string "על עצמכם.\p$"

gOakText_AskPlayerName::
    .string "בואו נתחיל עם שמך.\n"
    .string "מהו?\p$"

gOakText_FinalizePlayerName::
    .string "הבנתי…\n"
    .string "אז שמך {PLAYER}.$"

gOakText_IntroduceRival::
    .string "זהו הנכד שלי.\pאתם והוא יריבים מאז שהייתם\n"
    .string "תינוקות.\p…אמממ, מה היה שמו?$"

gOakText_AskRivalName::
    .string "השם של היריב שלכם, מה הוא היה?$"

gOakText_ConfirmRivalName::
    .string "…אממ, זה היה {RIVAL}?$"

gOakText_RememberRivalName::
    .string "אהה נכון! עכשיו אני נזכר!\n"
    .string "שמו הוא {RIVAL}!\p$"

gOakText_LegendAboutToUnfold::
    .string "{PLAYER}!\pאגדת הפוקימונים שלך ממש\n"
    .string "עומדת להיפתח!\pעולם של חלומות והרפתקאות\n"
    .string "עם פוקימונים מחכה! בואו נתחיל!$"
