PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "אמא: …טוב.\n"
    .string "כל הבנים עוזבים מתישהו.\l"
    .string "אמרו זאת בטלויזיה.\p"
    .string "אהה רגע... פרופסור אלון חיפש אותך,\n"
    .string "הוא בבית ליד.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "אמא: …טוב.\n"
    .string "כל הבנות חולמות על לטייל.\l"
    .string "אמרו זאת בטלויזיה.\p"
    .string "אהה רגע... פרופסור אלון חיפש אותך,\n"
    .string "הוא בבית ליד.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "אמא: {PLAYER}!\n"
    .string "לא לשכוח לנוח.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "אמא: או יופי! אתה והפוקימון\n"
    .string "שלך נראים נהדר.\l"
    .string "תשמרו על עצמיכם!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "יש סרט בטלויזיה.\n"
    .string "ארבעה ילדים הולכים על\l"
    .string "פסי רכבת.\p"
    .string "…כדאי שגם אני אלך.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "יש סרט בטלויזיה.\n"
    .string "ילדה עם צמות הולכת\l"
    .string "לצד הכביש.\p"
    .string "…כדאי שגם אני אלך.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "אופס, טעות בצד…$"

